### ISSUE TITLE
Not working in Python 3.5 virtualenv

### ISSUE THREAD

**Issue by foxmadr** [ambitioninc/pip-conflict-checker#12]
I'm getting the following error when running pipconflictchecker:

File "pyenv/lib/python3.5/site-packages/pipconflictchecker/checker.py", line 279, in main
File "pyenv/lib/python3.5/site-packages/pipconflictchecker/checker.py", line 244, in get_conflicts
File "pyenv/lib/python3.5/site-packages/pipconflictchecker/checker.py", line 208, in get_requirement_versions
"AttributeError: module 'pip' has no attribute 'get_installed_distributions"

pip is in ./pyenv/lib/python3.5/site-packages (19.1.1)

**Comment by somewes** [comment]
newer versions of pip should be supported in 0.6.0 of this project, but you can use ```pip check``` to do the same thing as this package.
